include:
- project: gardenlinux/gardenlinux-package-build
  file: pipeline/pipeline-git.yml

variables:
  SOURCE_NAME: oras
  SOURCE_REPO: https://github.com/oras-project/oras.git
  SOURCE_APT_INSTALL: golang-go
  BUILD_REQUIRES_GO: 'yes'
  BUILD_GOLANG_DIST: sid
  BUILD_GO_VERSION: "1.20"
  BUILD_GOLANG_PKG_NAME: golang-1.20-go
  BUILD_REQUIRES_GO: "yes"

